image: node:latest

variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
    - build
    - test
    - aws-init
    - deploy-dev
    - deploy-prod

cache:
    paths:
        - node_modules/

build:
    stage: build
    script:
        - npm install
        - npm run-script build

test:
    stage: test
    script:
        - echo "Running react test suite......"

aws-init:
    stage: aws-init
    script:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        - unzip awscliv2.zip
        - export PATH=$PATH:$PWD/aws/dist

deploy-dev:
    stage: deploy-dev
    script:
        - npm run-script deploy-dev

deploy-prod:
    stage: deploy-prod
    script:
        - npm run-script deploy
