image: node:latest

variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: us-west-2

stages:
    - build
    - test
    - deploy-dev
    - deploy-prod

cache:
    paths:
        - node_modules/

build:
    stage: build
    script:
        - npm install
        - npm run-script build
    artifacts:
        paths:
            - build
        expire_in: 10 minutes

test:
    stage: test
    script:
        - echo "Running react test suite......"

deploy-dev:
    stage: deploy-dev
    image: amazon/aws-cli
    only:
        - develop
    script:
        - npm run-script deploy

deploy-prod:
    stage: deploy-prod
    image: amazon/aws-cli
    only:
        - master
    script:
        - npm run-script deploy
