image: node:latest

variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
    - aws-init
    - build-dev
    - test-dev
    - deploy-dev
    - switch
    - build-prod
    - test-prod
    - deploy-prod

cache:
    paths:
        - node_modules/

aws-init:
    stage: aws-init
    script:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "../awscliv2.zip"
        - unzip ../awscliv2.zip -d ../
        - sudo ../aws/install

build-dev:
    stage: build-dev
    script:
        - npm install
        - npm run-script build

test-dev:
    stage: test-dev
    script:
        - echo "Running react test suite......"

deploy-dev:
    stage: deploy-dev
    script:
        - npm run-script deploy-dev

switch:
    stage: switch
    script:
        - git checkout -f master

build-prod:
    stage: build-dev
    script:
        - npm install
        - npm run-script build

test-prod:
    stage: test-prod
    script:
        - echo "Running react test suite......"

deploy-prod:
    stage: deploy-prod
    script:
        - npm run-script deploy
