image: node:latest

variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

stages:
    - aws-init
    - build
    - test
    - deploy-dev
    - deploy-prod

cache:
    paths:
        - node_modules/

aws-init:
    stage: aws-init
    script:
        - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "../awscliv2.zip"
        - unzip ../awscliv2.zip -d /tmp
        - /tmp/aws/install -i /tmp/acli -b /tmp/acli

build:
    stage: build
    script:
        - npm install
        - npm run-script build

test:
    stage: test
    script:
        - echo "Running react test suite......"

deploy-dev:
    stage: deploy-dev
    only:
        - develop
    script:
        - alias aws=/tmp/acli/aws
        - npm run-script deploy-dev

deploy-prod:
    stage: deploy-prod
    only:
        - master
    script:
        - alias aws=/tmp/acli/aws
        - npm run-script deploy
